const constants = {
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGIN_PENDING: 'LOGIN_PENDING',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	ITEMS_ERROR: 'ITEMS_ERROR',
	ITEMS_PENDING: 'ITEMS_PENDING',
	ITEMS_SUCCESS: 'ITEMS_SUCCESS',
	CATEGORY_ERROR: 'CATEGORY_ERROR',
	CATEGORY_PENDING: 'CATEGORY_PENDING',
	CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
	SINGLE_ERROR: 'SINGLE_ERROR',
	SINGLE_PENDING: 'SINGLE_PENDING',
	SINGLE_SUCCESS: 'SINGLE_SUCCESS',
	FAQ_ERROR: 'FAQ_ERROR',
	FAQ_PENDING: 'FAQ_PENDING',
	FAQ_SUCCESS: 'FAQ_SUCCESS',
};

export default constants;
